const profiles = {
  rpc: {
    mainnet: [
      { endpoint: 'https://seed1.switcheo.network:10331' },
      { endpoint: 'https://seed2.switcheo.network:10331' },
      { endpoint: 'https://seed3.switcheo.network:10331' },
      { endpoint: 'https://seed4.switcheo.network:10331' },
      { endpoint: 'https://seed5.switcheo.network:10331' },
      { endpoint: 'https://seed1.cityofzion.io:443' },
      { endpoint: 'https://seed2.cityofzion.io:443' },
      { endpoint: 'https://seed3.cityofzion.io:443' },
      { endpoint: 'https://seed4.cityofzion.io:443' },
      { endpoint: 'https://seed5.cityofzion.io:443' },
      { endpoint: 'https://seed6.cityofzion.io:443' },
      { endpoint: 'https://seed7.cityofzion.io:443' },
      { endpoint: 'https://seed8.cityofzion.io:443' },
      { endpoint: 'https://seed9.cityofzion.io:443' },
      { endpoint: 'https://seed0.cityofzion.io:443' },
      { endpoint: 'http://node1.ams2.bridgeprotocol.io' },
      { endpoint: 'http://node2.ams2.bridgeprotocol.io' },
      { endpoint: 'http://node1.nyc3.bridgeprotocol.io' },
      { endpoint: 'http://node2.nyc3.bridgeprotocol.io' },
      { endpoint: 'http://node1.sgp1.bridgeprotocol.io' },
      { endpoint: 'http://node2.sgp1.bridgeprotocol.io' },
      { endpoint: 'https://seed1.redpulse.com:443' },
      { endpoint: 'https://seed2.redpulse.com:443' },
      { endpoint: 'http://seed1.aphelion-neo.com:10332' },
      { endpoint: 'http://seed2.aphelion-neo.com:10332' },
      { endpoint: 'http://seed3.aphelion-neo.com:10332' },
      { endpoint: 'http://seed4.aphelion-neo.com:10332' },
      { endpoint: 'http://seed1.ngd.network:10332' },
      { endpoint: 'http://seed2.ngd.network:10332' },
      { endpoint: 'http://seed3.ngd.network:10332' },
      { endpoint: 'http://seed4.ngd.network:10332' },
      { endpoint: 'http://seed5.ngd.network:10332' },
      { endpoint: 'http://seed6.ngd.network:10332' },
      { endpoint: 'http://seed7.ngd.network:10332' },
      { endpoint: 'http://seed8.ngd.network:10332' },
      { endpoint: 'http://seed9.ngd.network:10332' },
      { endpoint: 'http://seed10.ngd.network:10332' },
    ],
    testnet: [
      { endpoint: 'https://test1.cityofzion.io:443' },
      { endpoint: 'https://test2.cityofzion.io:443' },
      { endpoint: 'https://test3.cityofzion.io:443' },
      { endpoint: 'https://test4.cityofzion.io:443' },
      { endpoint: 'https://test5.cityofzion.io:443' },
    ],
  },
  assets: [
    { id: '0xc56f33fc6ecfcd0c225c4ab356fee59390af8560be0e930faebe74a6daff7c9b', name: 'NEO', symbol: 'NEO', type: 'GoverningToken', precision: 0 },
    { id: '0x602c79718b16e442de58778e148d0b1084e3b2dffd5de6b7b16cee7969282de7', name: 'GAS', symbol: 'GAS', type: 'UtilityToken', precision: 8 },
  ],
}

export default profiles
